### PR TITLE
args() function

### PR DESCRIPTION
**Pull request by sysread**
Adds a secondary syntax for calling `env` to set an environment variable. Also adds a new routine, `validateVarArgs`, to `functions.go` that validates multiple sets of calling semantics.

### CODE REVIEW

**Comment by odino** [comment]
LGTM. Can you send this PR to the `1.9.x` branch though?

**Comment by sysread** [comment]
Sure. It's a holiday in the US this weekend so I'll probably pick this up
on Monday.

**Comment by odino** [comment]
No worries, and happy thanksgiving a bit late!

**Comment by odino** [comment]
BTW lmk if you need some more time -- this week I intend to release 1.9. It would be great to include this feature but if you need some more time I'll go ahead and prepare a release, and include this in 1.10. No pressure, lmk!

**Comment by sysread** [comment]
I changed the pr target and resolved the conflicts. If you prefer, I can cherry pick to 1.9.x and submit as a new PR instead, although we'd lost the conversation history here.

**Comment by odino** [comment]
This is perfect, thanks :smile:

**Pull request merged**
